name: CI
on:
  pull_request:
jobs:
  ci-matrix:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 100
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: sbt ci ${{ github.ref }}
        run: sbt ci
  ci:
    runs-on: ubuntu-22.04
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
